<div class="alert alert-block alert-warning">
<img src="./Imagenes/ITESO_Logo.png" style="width:500px;height:142px;" title="Logo ITESO">
<br><font face = "Times New Roman" size = "6"><b><center>Maestría en Sistemas Computacionales</center></b></font>
<br><font face = "Times New Roman" size = "5"><b><center>Programación para Análisis de Datos</center></b></font>

<b><br><font face = "Times New Roman" size = "4"><center>Unidad 5: Proceso de Selección de Métodos</center></font>
<font face = "Times New Roman" size = "4"><center>Tema 5.4: Modelo K-Means</center></font>
<font face = "Times New Roman" size = "4"><center>Ejercicio del Modelo K-Means</center></font>
</div>

#### Nombre del Alumno: Miguel Angel Rubio Origel
#### Matrícula: CD723963
#### Posgrado de Adscripción: Maestria en Ciencia de Datos

#### Instrucciones:
Por favor, revisa cuidadosamente las siguientes instrucciones:

* Realiza este ejercicio de manera individual.
* Escribe tu nombre completo, matrícula y posgrado de adscripción en los campos correspondientes.
* Lee cuidadosamente cada uno de los ejercicios y realiza las acciones solicitadas.
* Coloca tu código ejecutable en las celdas debajo de la explicación de cada reactivo.
* Sube en CANVAS sólamente el archivo `.ipynb` en la liga correspondiente.

#### Explicación:
Se utilizarán como entradas un conjunto de datos en el que se analizaban rasgos de la personalidad de usuarios de **Twitter**. Se han filtrado a 140 personas reconocidas y de diversas partes del mundo en diferentes areas: deporte, cantantes, actores, etc. Basado en una metodología de **Psicología** conocida como *Las 5 Dimensiones de la Personalidad*, se obtiene un **DataFrame** del archivo `Ocean_Twitter.CSV` que contiene los siguientes encabezados de las columnas de información:

1. `usuario`: El nombre del usuario en Twitter (*texto*).
2. `op`: **Openness to experience** – Grado de apertura mental a nuevas experiencias (*flotante*).
3. `co`: **Conscientiousness** – Grado de orden y organización (*flotante*).
4. `ex`: **Extraversion** – Grado de timidez o participación ante el grupo social (*flotante*).
5. `ag`: **Agreeableness** – Grado de empatía con los demás y temperamento (*flotante*).
6. `ne`: **Neuroticism** – Grado de neuroticismo, nervioso, irritabilidad y seguridad en sí mismo (*flotante*).
7. `palabras`: Cantidad promedio de palabras usadas en sus Tweets (*flotante*).
8. `categoria`: Actividad laboral del usuario (actor, cantante, etc, es un valor *entero*).

Se utilizará el algoritmo **K-Means** para que agrupe estos usuarios por sus similitudes en la personalidad. 

**En problema consiste en determinar el grupo al que pertenece el usuario dependiendo de valores de personalidad específicos.**

In [3]:
#Importación de librerías
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

#Definición de los parámetros de los gráficos
plt.rcParams.update({'font.size': 11, 'figure.figsize': (16, 9)}) 
plt.style.use('ggplot')

#Lectura del DataSet
datos_df = pd.read_csv("Ocean_Twitter.csv")

**1.** Definir la estructura de datos que se utilizará para alimentar el algoritmo, empleando las 5 columnas de información (`op`, `co`, `ex`, `ag` y `ne`) en la variable X, y la columna `categoria` en la variable *y*, las cuales se convierten en arreglos de **NumPy**:

In [4]:
# Código del Reactivo 1

#Definición de los valores X e y
X = np.array(datos_df[['op','ex','ag','co','ne']])
y = np.array(datos_df['categoria'])

**2.** Ejecutar el algoritmo para 3 clústers (*K = 3*) obteniendo las etiquetas e imprimiendo los centroides:

In [5]:
# Código del Reactivo 2

#Importación de librerías
from sklearn.cluster import KMeans

#Aplicación del Modelo K-Means
kmeans = KMeans(n_clusters = 3).fit(X)
centroids = kmeans.cluster_centers_
print("Los valores de los centroides son: \n", centroids)

Los valores de los centroides son: 
 [[44.8510553  39.43866323 19.87397079 24.8031376   9.17429846]
 [36.42402048 46.7349062  31.93118182 18.58415332  7.39443677]
 [56.76199819 34.22990819 15.86322912 25.49525258  5.86375296]]


**3.** Mostrar cuántos usuarios tiene cada uno de los clústers:

In [6]:
# Código del Reactivo 3

#Etiquetas de cada punto de los datos
labels = kmeans.predict(X)

#Copia de los Usuarios junto con su respectivo Clúster (label)
copy = pd.DataFrame()
copy['usuario'] = datos_df['usuario'].values
copy['categoria'] = datos_df['categoria'].values
copy['label'] = labels;

#Conteo de Usuarios por cada Clúster (label)
cantidadGrupo =  pd.DataFrame()
cantidadGrupo['color'] = ['rojo', 'verde', 'azul']
cantidadGrupo['cantidad'] = copy.groupby('label').size()

#Impresión de los Resultados
print("La cantidad de usuarios en cada clúster es:")
display(cantidadGrupo)

La cantidad de usuarios en cada clúster es:


color  cantidad
0   rojo        70
1  verde        44
2   azul        26

**4.** Mostrar la cantidad de usuarios en el clúster número 1 y sus categorías:

In [8]:
# Código del Reactivo 4

#Copia de los Usuarios contenidos en el Clúster 
group_referrer_index = copy['label'] == 1
group_referrals = copy[group_referrer_index]

#Conteo de Usuarios contenidos en el Clúster 
diversidadGrupo =  pd.DataFrame()
diversidadGrupo['Categoria'] = [0,1,2,3,4,5,6,7,8,9]
diversidadGrupo['Descripción'] = ['','Actor/Actriz', 'Cantante', 'Modelo', 'Televisión/Series', 'Radio', 'Tecnología', 'Deportes', 'Política', 'Escritor']
diversidadGrupo['Cantidad'] = group_referrals.groupby('categoria').size()
diversidadGrupo.set_index('Categoria', inplace = True)
diversidadGrupo.drop(index = 0, inplace = True)

#Impresión de los Resultados
print("La cantidad total de usuarios en el cluster 1 es:", cantidadGrupo.iloc[1].loc['cantidad'])
print("La categoría de los usuarios en el clúster 1 es:")
display(diversidadGrupo)

La cantidad total de usuarios en el cluster 1 es: 44
La categoría de los usuarios en el clúster 1 es:


Descripción  Cantidad
Categoria                             
1               Actor/Actriz       5.0
2                   Cantante       7.0
3                     Modelo       NaN
4          Televisión/Series      13.0
5                      Radio       3.0
6                 Tecnología       1.0
7                   Deportes       7.0
8                   Política       5.0
9                   Escritor       3.0

**5.** Para los valores (`op`, `co`, `ex`, `ag` y `ne`) definidos a continuación en relación a un nuevo usuario que se quiere clasificar, determinar el clúster al que pertenece: 

* `op` = 12.65
* `co` = 45.34
* `ex` = 67.89
* `ag` = 43.21
* `ne` = 22.56

In [9]:
# Código del Reactivo 5

#Clasificación de nuevas muestras
X_new = np.array([[12.65, 45.34, 67.89, 43.21, 22.56]]) 
new_labels = kmeans.predict(X_new)

#Impresión de los Resultados
print("El nuevo usuario pertenece al Clúster número:", new_labels)

El nuevo usuario pertenece al Clúster número: [1]


<div class="alert alert-block alert-danger">
<b>.: Fin del Ejercicio :.</b>
</div>